INSERT INTO languages ('qid', 'wikipedia_url', 'en_label') VALUES
    ('Q21117', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_i%C3%BApique_do_Alasca_Central', 'Central Alaskan Yupik'),
    ('Q4023175', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_yudj%C3%A1', 'Jurúna'),
    ('Q8785', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_arm%C3%AAnia', 'Armenian'),
    ('Q33239', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_cebuana', 'Cebuano'),
    ('Q12640969', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_rajbanshi', 'Rajbanshi Language'),
    ('Q3450493', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_uapixana', 'Wapishana'),
    ('Q35035', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_aja_(nigero-congolesa)', 'Adja'),
    ('Q1875885', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_ambai', 'Ambai'),
    ('Q8044571', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_asurini_do_Xingu', 'Xingú Asuriní'),
    ('Q5646', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_atong', 'A Tong'),
    ('Q34954', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_bekwarra', 'Bekwarra'),
    ('Q3912758', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_bondum', 'Bondum Dogon'),
    ('Q33522', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_cabardiana', 'Kabardian'),
    ('Q5100112', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_chinanteca_de_Palantla', 'Chinantec of Palantla'),
    ('Q32979', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_choctaw', 'Choctaw'),
    ('Q34015', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_crioula_de_Seicheles', 'Seychellois Creole'),
    ('Q2980381', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_ese_ejja', 'Ese Ejja'),
    ('Q35272', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_goemai', 'Goemai'),
    ('Q25355', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_groenlandesa', 'Greenlandic'),
    ('Q56421', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_hopi', 'Hopi'),
    ('Q33509', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_inguche', 'Ingush'),
    ('Q3695193', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_kurt%C3%B6p', 'Kurtöp'),
    ('Q33698', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_livoniana', 'Livonian'),
    ('Q2655664', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_lokono', 'Arawak'),
    ('Q36213', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_maduresa', 'Madurese'),
    ('Q34214', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_monguor', 'Monguor'),
    ('Q34226', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_neoaramaica_ocidental', 'Western Neo-Aramaic'),
    ('Q5908646', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_ngkolmpu', 'Kanum'),
    ('Q72695', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_nung_(tai)', 'Nung'),
    ('Q2992876', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_Nuu-chah-nulth', 'Nuu-chah-nulth'),
    ('Q13260', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_pai%C3%BAte_meridional', 'Colorado River Numic'),
    ('Q36699', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_pijin', 'Pijin'),
    ('Q13199', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_romanche', 'Romansh'),
    ('Q33954', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_sango', 'Sango'),
    ('Q7532519', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_siwai', 'Siwai'),
    ('Q34067', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_suana', 'Svan'),
    ('Q638300', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_timucua', 'Timucua'),
    ('Q36645', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_toqabaqita', 'To’abaita'),
    ('Q12294279', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_trumai', 'Trumai'),
    ('Q34251', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_t%C3%BAlu', 'Tulu'),
    ('Q35524', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_yalunka', 'Yalunka'),
    ('Q56545', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_yukaghir_de_Kolyma', 'Southern Yukaghir'),
    ('Q10199', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_zaza', 'Zazaki'),
    ('Q9078', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_let%C3%A3', 'Latvian'),
    ('Q13267', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_cingalesa', 'Sinhala'),
    ('Q3450504', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_res%C3%ADgaro', 'Resígaro'),
    ('Q27709', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_de_sinais_de_Adamorobe', 'Adamorobe Sign Language'),
    ('Q35472', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_ik', 'Ik'),
    ('Q34016', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_sandawe', 'Sandawe'),
    ('Q9246', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_mongol', 'Mongolian'),
    ('Q35950', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_chiman%C3%A9', 'Chimane'),
    ('Q2748232', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_nung_(sino-tibetana)', 'Nung'),
    ('Q36939', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_vai', 'Vai'),
    ('Q36414', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_pocomchi', 'Poqomchi'),
    ('Q2640646', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_yuracar%C3%A9', 'Yuracaré'),
    ('Q25289', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_c%C3%B3rnica', 'Cornish'),
    ('Q35990', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_lepcha', 'Lepcha'),
    ('Q2393095', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_o%27odham', 'O odham'),
    ('Q3200839', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_quasa', 'Kwaza'),
    ('Q3192336', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_camaiur%C3%A1', 'Kamayurá'),
    ('Q27811', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_afar', 'Afar'),
    ('Q770547', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_lavukaleve', 'Lavukaleve'),
    ('Q6380372', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_caiabi', 'Kayabi'),
    ('Q27183', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_inupiaque', 'Iñupiaq'),
    ('Q3143384', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_hupd%C3%A1', 'Hup'),
    ('Q35876', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_guarani', 'Guarani'),
    ('Q36163', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_curda_setentrional', 'Kurmanji'),
    ('Q11732444', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_menya', 'Menya'),
    ('Q56329', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_totonaca_de_Papantla', 'Papantla Totonac'),
    ('Q3130296', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_savosavo', 'Savosavo'),
    ('Q2375468', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_bora', 'Bora'),
    ('Q27792', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_tlingit', 'Tlingit'),
    ('Q7636341', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_sulka', 'Sulka'),
    ('Q13893353', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_caapor', 'Urubú-Kaapor'),
    ('Q33467', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_mam', 'Mam'),
    ('Q56727', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_murle', 'Murle'),
    ('Q85874983', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_puyuma', 'Puyuma'),
    ('Q3915562', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_kharia', 'Kharia'),
    ('Q35288', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_crioula_de_Bioco', 'Pichinglis'),
    ('Q2981620', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_mats%C3%A9', 'Matsés'),
    ('Q34129', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_tigr%C3%A9', 'Tigre'),
    ('Q1564258', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_nenets_da_tundra', 'Tundra Nenets'),
    ('Q8097', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_telugo', 'Telugu'),
    ('Q13238', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_udmurte', 'Udmurt'),
    ('Q36568', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_tadaksahak', 'Tadaksahak'),
    ('Q56362', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_luwo', 'Luwo'),
    ('Q35573', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_huasteca', 'Teenek'),
    ('Q5224058', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_darma', 'Darmiya'),
    ('Q27175', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_fr%C3%ADsia_ocidental', 'West Frisian'),
    ('Q13203', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_rotokas', 'Rotokas'),
    ('Q3026110', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_yaminaua', 'Yaminawa'),
    ('Q33265', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_cheyenne', 'Cheyenne'),
    ('Q3397346', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_rennellesa', 'Rennellese'),
    ('Q7930', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_malgaxe', 'Malagasy'),
    ('Q2883843', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_barasana-eduria', 'Barasana-Eduria'),
    ('Q2669219', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_guniyandi', 'Guniyandi'),
    ('Q33779', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_saramacana', 'Saramaccan'),
    ('Q34992', 'https://pt.wikipedia.org/wiki/Crioulo_de_Ano-Bom', 'Annobonese Creole'),
    ('Q9252', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_cazaque', 'Kazakh'),
    ('Q1659701', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_movima', 'Movima'),
    ('Q4784535', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_arawet%C3%A9', 'Araweté'),
    ('Q1526530', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_aguaruna', 'Aguaruna'),
    ('Q36962', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_aqu%C3%A9m', 'Xavante'),
    ('Q2859081', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_apurin%C3%A3', 'Apurinã'),
    ('Q4829584', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_av%C3%A1-canoeira', 'Avá-Canoeiro'),
    ('Q5359560', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_cashibo', 'Kashibo'),
    ('Q33317', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_cocama', 'Cocama'),
    ('Q3042278', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_macu-cam%C3%A3', 'Dâw'),
    ('Q962392', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_desana', 'Desano'),
    ('Q2665734', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_caingangue', 'Kaingang'),
    ('Q3112184', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_caritiana', 'Karitiâna'),
    ('Q3194265', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_catuquina-pano', 'Waninnawa'),
    ('Q2640935', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_murui_huitoto', 'Murui Huitoto'),
    ('Q2068190', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_nambiquara', 'Nambikwara'),
    ('Q34333', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_nheengatu', 'Nheengatu'),
    ('Q33856', 'https://pt.wikipedia.org/wiki/Papiamento', 'Papiamento'),
    ('Q2585357', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_ricbacta', 'Rikbaktsa'),
    ('Q7684673', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_tapirap%C3%A9', 'Tapirapé'),
    ('Q732726', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_tariana', 'Tariana'),
    ('Q3314742', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_terena', 'Terêna'),
    ('Q3566001', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_uanano', 'Wanano'),
    ('Q3027930', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_xoclengue', 'Xokleng'),
    ('Q30005', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_jeje', 'Ewe'),
    ('Q3915451', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_guari', 'Gwari'),
    ('Q56475', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_hau%C3%A7%C3%A1', 'Hausa'),
    ('Q36302', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_oko', 'Oko'),
    ('Q34065', 'https://pt.wikipedia.org/wiki/L%C3%ADnguas_tuaregues', 'Tuareg'),
    ('Q36991', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_zialo', 'Zialo'),
    ('Q33445', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_jibbali', 'Shehri'),
    ('Q5137', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_guzerate', 'Gujarati'),
    ('Q13361', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_mehri', 'Mehri'),
    ('Q56844', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_namuyi', 'Namuyi'),
    ('Q35043', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_bukawa', 'Bukawa'),
    ('Q3507895', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_bukiyip', 'Bukiyip'),
    ('Q5350305', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_ekari', 'Ekari'),
    ('Q33295', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_fijiana', 'Fijian'),
    ('Q9237', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_malaia', 'Malay'),
    ('Q33947', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_lap%C3%B4nica_setentrional', 'Northern Sami'),
    ('Q3438373', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_catuquina-canamari', 'Kanamarí'),
    ('Q30719984', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_tapayuna', 'Tapayuna'),
    ('Q33690', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_cass%C3%BAbia', 'Kashubian'),
    ('Q4701960', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_acuntsu', 'Akuntsu'),
    ('Q3029682', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_maxacali', 'Maxakalí'),
    ('Q3361895', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_panar%C3%A1', 'Panara'),
    ('Q746723', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_mundurucu', 'Munduruku'),
    ('Q9240', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_indon%C3%A9sia', 'Indonesian'),
    ('Q56865', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_uaimiri-atroari', 'Waimiri-Atroarí'),
    ('Q33882', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_macua', 'Makhuwa'),
    ('Q9610', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_bengali', 'Bangla'),
    ('Q36983', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_umbundo', 'Umbundu'),
    ('Q3162245', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_japhug', 'Japhug'),
    ('Q33569', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_havaiana', 'Hawaiian'),
    ('Q3460478', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_saban%C3%AA', 'Sabanês'),
    ('Q36137', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_garo', 'Garo'),
    ('Q2520538', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_tuiuca', 'Tuyuca'),
    ('Q5885', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_t%C3%A2mil', 'Tamil'),
    ('Q56688', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_alamblak', 'Alamblak'),
    ('Q3299145', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_matis', 'Matis'),
    ('Q33243', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_bambara', 'Bambara'),
    ('Q10179', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_zulu', 'Zulu'),
    ('Q33673', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_canaresa', 'Kannada'),
    ('Q5211943', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_crioula_indo-portuguesa_de_Dam%C3%A3o_e_Diu', 'Daman and Diu Portuguese Creole'),
    ('Q4356223', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_kano%C3%AA', 'Kanoê'),
    ('Q2786408', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_bumthang', 'Bumthang'),
    ('Q7022547', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_ngoni', 'Ngoni'),
    ('Q774441', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_yat%C3%AA', 'Fulniô'),
    ('Q9186', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_cantonesa', 'Cantonese'),
    ('Q9211', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_laociana', 'Lao'),
    ('Q12175', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_manesa', 'Manx'),
    ('Q3101212', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_caiap%C3%B3', 'Mẽbêngôkre'),
    ('Q34311', 'https://pt.wikipedia.org/wiki/L%C3%ADngua_iorub%C3%A1', 'Yoruba'),
    ('Q7918', 'https://en.wikipedia.org/wiki/Bulgarian_phonology', 'Bulgarian'),
    ('Q727694', 'https://en.wikipedia.org/wiki/Standard_Chinese', 'Standard Mandarin'),
    ('Q9056', 'https://en.wikipedia.org/wiki/Czech_phonology', 'Czech'),
    ('Q7411', 'https://en.wikipedia.org/wiki/Dutch_phonology', 'Dutch'),
    ('Q9072', 'https://en.wikipedia.org/wiki/Estonian_phonology', 'Estonian'),
    ('Q1412', 'https://en.wikipedia.org/wiki/Finnish_phonology', 'Finnish'),
    ('Q150', 'https://en.wikipedia.org/wiki/French_phonology', 'French'),
    ('Q188', 'https://en.wikipedia.org/wiki/Standard_German_phonology', 'German'),
    ('Q9288', 'https://en.wikipedia.org/wiki/Modern_Hebrew_phonology', 'Hebrew'),
    ('Q9067', 'https://en.wikipedia.org/wiki/Hungarian_phonology', 'Hungarian'),
    ('Q5287', 'https://en.wikipedia.org/wiki/Japanese_phonology', 'Japanese'),
    ('Q9176', 'https://en.wikipedia.org/wiki/Korean_phonology', 'Korean'),
    ('Q9168', 'https://en.wikipedia.org/wiki/Persian_phonology', 'Persian'),
    ('Q809', 'https://en.wikipedia.org/wiki/Polish_phonology', 'Polish'),
    ('Q5146', 'https://en.wikipedia.org/wiki/Portuguese_phonology', 'Portuguese'),
    ('Q7913', 'https://en.wikipedia.org/wiki/Romanian_phonology', 'Romanian'),
    ('Q7737', 'https://en.wikipedia.org/wiki/Russian_phonology', 'Russian'),
    ('Q9063', 'https://en.wikipedia.org/wiki/Slovene_phonology', 'Slovene'),
    ('Q1321', 'https://en.wikipedia.org/wiki/Spanish_phonology', 'Spanish'),
    ('Q9027', 'https://en.wikipedia.org/wiki/Swedish_phonology', 'Swedish'),
    ('Q9217', 'https://en.wikipedia.org/wiki/Thai_language', 'Thai'),
    ('Q8798', 'https://en.wikipedia.org/wiki/Ukrainian_phonology', 'Ukrainian'),
    ('Q9199', 'https://en.wikipedia.org/wiki/Vietnamese_phonology', 'Vietnamese'),
    ('Q33823', 'https://en.wikipedia.org/wiki/Nepali_phonology', 'Nepali'),
    ('Q9166', 'https://en.wikipedia.org/wiki/Maltese_language', 'Maltese');
