SELECT ?phoneme ?phonemeLabel (group_concat(?ipa; separator=" ") AS ?transcriptions) ?audio
WHERE
{
  ?phoneme wdt:P279* wd:Q202064.
  ?phoneme wdt:P898 ?ipa.
  FILTER NOT EXISTS { wd:$1 wdt:P2587 ?phoneme. }
  OPTIONAL { ?phoneme wdt:P51 ?audio. }
  SERVICE wikibase:label { bd:serviceParam wikibase:language "en". }
}
GROUP BY ?phoneme ?phonemeLabel ?audio
ORDER BY ?phonemeLabel
